### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by yadudoc** [FaaSr/FaaSr-package#107]
I'm reviewing this package as part of your JOSS submission. So far things look great, and I have a few items pending that I'm trying to figure out. I notice that the repo does not have a `CONTRIBUTING.md` document that github recommends. You might already have all this material in project documentation, even so, I would highly recommend adding this material to a dedicated `CONTRIBUTING.md` file.

Adding breadcrumbs: openjournals/joss-reviews#7027

**Comment by renatof** [comment]
thank you, @yadudoc - we will add this file shortly and let you know once it's there

**Comment by renatof** [comment]
FYI @yadudoc I've added the CONTRIBUTING.md file to the main repo. thank you!

**Comment by yadudoc** [comment]
Nicely done! I'm marking this issue as done.
