### ISSUE TITLE
fix(paths): Preserve leading slash in local absolute paths

### ISSUE THREAD

**Issue by Ashish-Ramrakhiani** [FaaSr/FaaSr-package#120]
## Description
The preprocessing step in `faasr_get_file` and `faasr_put_file` functions incorrectly trims leading slashes from local folder paths, which can break functionality when using absolute paths.

## Current Behavior
When providing an absolute path in `local_folder`:
```r
local_folder <- "/tmp/xyz"
# After preprocessing
local_folder becomes "tmp/xyz"  # Leading slash removed
```

## Expected Behavior
```r
local_folder <- "/tmp/xyz"
# After preprocessing
local_folder should remain "/tmp/xyz"  # Leading slash preserved

# For multiple leading slashes
local_folder <- "///tmp/xyz"
# Should normalize to
local_folder becomes "/tmp/xyz"  # Single leading slash preserved
```

**Comment by renatof** [comment]
Fixed in release 1.4.3
