### ISSUE TITLE
Fix support for non-AWS S3 servers such as minio

### ISSUE THREAD

**Issue by renatof** [FaaSr/FaaSr-package#19]
This involves changes to schema and paws::s3 configuration to support non-AWS servers such as minio

By default, paws uses AWS S3. To use other providers, including minio, we need to do the following changes:
1) remove "Protocol" from the JSON schema (it will be encoded in the endpoint, e.g. http://address or https://address)
2) make "Endpoint" optional instead of mandatory in the JSON schema
3) use endpoint key in paws::s3 only if it's declared, i.e:
*if* the user declared "Endpoint" in the payload, add it to the S3 configuration, as per snippet below; 
*else*, don't  add the endpoint to the configuration
  s3<-paws::s3(
    config=list(
	  credentials=list(
	    creds=list(
		  access_key_id=target_s3$AccessKey,
		  secret_access_key=target_s3$SecretKey
		)
	  ),
          endpoint=target_s3$Endpoint,
	  region=target_s3$Region
	)
  )

**Comment by spark0510** [comment]
What about the "Writable"? Do we still need this?

**Comment by renatof** [comment]
yes, let's keep it. it can be optional, and if it's set to "no" return an error if the user tries to use it for logs and/or to do a put_file operation

**Comment by renatof** [comment]
Implemented and tested
