### ISSUE TITLE
Implement a check for aliveness of s3 servers

### ISSUE THREAD

**Issue by renatof** [FaaSr/FaaSr-package#20]
Need to implement a new function faasr_s3_check(faasr) in a separate file faasr_s3_check.R
It will be called from faasr_start after parsing and checking for cycles
This function iterates over all DataStores the user declares and attempts to list the top-level bucket for each one; if a S3 data store returns an error, cat() out to the user an error message like:
"faasr_s3_check: S3 server " + namefromparsedJSON + " failed with message: " + error message from paws

**Comment by spark0510** [comment]
- faasr_s3_check() has been implemented for this issue.
