### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by renatof** [FaaSr/FaaSr-package#24]
We need to provide error messages that help users identify problems, especially when we receive error messages from other runtime systems (e.g. from R, or from paws, or from AWS/github/openwhisk)

**Comment by spark0510** [comment]
[error in the github_token] 
If there's an error in given token, it makes a following error from github.

Error: 
JSON: “My_Github_Account”: {“Token”:”invalid token”}

Result:
[1] "Error: Client error: (401) Unauthorized"
Error: Process completed with exit code 1.

Solution:
1. Catch "Status 401: Bad Credentials" in "faasr_trigger"

**Comment by spark0510** [comment]
[error in the github_ref] 
If there’s an error in the ref, it makes an infinite loop when invoking the next action in the github. Eventually github returns a timeout error. 

Error:
JSON: “My_Github_Account”:{“Ref”:”invalid ref such as branch345”}

Result:
Error in curl::curl_fetch_memory(url, handle = handle) : 
Timeout was reached: [35.85.55.1:9000] Connection timeout after 60001 ms
Calls: faasr_start ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.

Solution:
1. Check "Status 422: No ref" in "faasr_trigger"

**Comment by spark0510** [comment]
[error in the github_workflow] 
If there’s an error in the workflow name, it makes an infinite loop when invoking the next action in the github. Eventually github returns a timeout error.

Error:
JSON: “My_Github_Account”:{“WorkflowName”:”wrong_workflow_name.yml”}
Github: ./github/workflows/correct_workflow_name.yml

Result:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [35.85.55.1:9000] Connection timeout after 60001 ms
Calls: faasr_start ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.

Solution:
1. Check "Status 404: Not found" in "faasr_trigger"

**Comment by spark0510** [comment]
[error in the get(“name of the function”)] 
If the name of the function doesn’t exist in the container(it hasn’t been downloaded from the github), it returns a following message, but it falls into the infinite loop.

Error: 
JSON: FunctionGitRepo:{“wrong_function_name”:”wrong_git_url”}

Result:
Openwhisk: stderr: Error in get(faasr$FunctionInvoke) : object 'prepare_data' not found
GithubActions: Infinite loop(Timeout Error)

Solution:
1. use try/catch function: check <- tryCatch(expr=get(faasr$FunctionInvoke), error=function(e){ cat("error_msg") /n stop()})
   -pros: reliable 
   -cons: overhead
2. error result of get() is NULL, which means empty. Check whether the result is empty and if it is true, return error msg.
   -pros: simple
   -cons: unreliable(if result is filled with previous function name, it will not return the error msg)

**Comment by spark0510** [comment]
[error in the openwhisk_Namespace] 
If there’s an error/mistake in the namespace, the function stops without leaving any error in the log when invoking the next action. The IBMcloud leaves the following error message, but only looking into the activation logs can detect this error message.

Error:
“Namespace”:”wrong_namespace”

Result:
{"code":"01168d836cc6cec758ffbd2543e9fa60","error":"The supplied authentication is not authorized to access ‘wrong_namespace/functionname'."}

**Comment by spark0510** [comment]
[error in the Openwhisk_Region] 
If there’s an error/mistake in the region, the function stops without leaving any error in the log when invoking the next action. The IBMcloud leaves the following error message, but no details are included.

e.g. 
Error:
"Region": "us-eats-1."

Result:
"error": "The action did not return a dictionary or array."

**Comment by spark0510** [comment]
[error in the function_Arguments]If there’s an error/mistake in the Arguments of the function, the function stops without leaving any error in log when trying to access remote storage. The Storage may leave the following error message(this example, S3), while file doesn’t exist. This error is related to the “faasr_get_file” function.

Error:
JSON: FunctionList:{Functionname:{“Arguments”:”input1”:”wrong_name”}}

Result:
Openwhisk: stderr: Error: SerializationError (HTTP 404). failed to read from query HTTP response body
GithubActions: Infinite loop(Timeout error)

Solution:
1. use try/catch function: check <- tryCatch(expr=s3$download_file(), error=function(e){ cat("error_msg") /n
   stop()}

**Comment by spark0510** [comment]
[error in the InvokeNext] If there’s an error/mistake in the function names of InvokeNext array, the function stops without leaving any error in log when invoking next function.

Error:
JSON:FunctionList:{Functionname:{“InvokeNext”:[“wrong_name”]}}

Result:
Openwhisk : No errors, just skip the action
GithubActions: Infinite loop(Timeout error)

Solution:
1. Check non reachable state in "check_workflow_cycle"
2. In case of GithubActions, check "Status 404: Not found" in "faasr_trigger"

**Comment by nanmu08** [comment]
Error For AWS Lambda

1. [Error in trigger next function] There isn't a matching lambda function name for the function name defined in payload.json.
    For example: there is a lambda function "compute_product", but in payload:
"FunctionList": {
        "prepare_data": {
            "FaaSServer": "lambda_a",
            "InvokeNext": [
                "compute_division",
                "**compute_production**"
            ]
        },
        "**compute_production**": {
           .........
            }

 [ Error ]: no relevant log in FaaSrLog, in AWS CloudWatch, log message: [ERROR] Exception: Error executing R script. Stdout: NULL


2. [Error in trigger next function] Lmabda server SecretKey or AccessKey in payload "ComputeServers" part is wrong.

 [Error]: no relevant log in FaaSrLog, 
  in AWS CloudWatch, log message for SecretKey: [Error: InvalidSignatureException (HTTP 403). The request signature we calculated does not match the signature you provided.]
  in AWS CloudWatch, log message for AccessKey:  Error: UnrecognizedClientException (HTTP 403). The security token included in the request is invalid.



3. [Error for S3 Storage] there is a S3 bucket(name A) create in us-east-1.  But in payload.json in "DataStores" part, bucket A region is us-east-2.

[Error]: In FaaSrLog,  {"faasr_start":"Errors in the user function: prepare_data "}, no relevant info showsthe bucket region is wrong.



4. [Error in install package] the packages which are defined in payload.json “FunctionCRANPackage” part cannot install.

[Error]: in AWS CloudWatch, some relevant log message:

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages(package) :
'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(package) : unable to install packages

**Comment by spark0510** [comment]
Error For AWS Lambda
1.
Solution: 
Checking Unreachable state in check_workflow_cycle

2.
Solution: TBD

3.
Solution: Checking S3 storage in check_s3_bucket

4.
Solution: Add new path "/tmp" to the path: .libPaths(), and install new library on "/tmp"
