### ISSUE TITLE
Improve credential management in Rstudio

### ISSUE THREAD

**Issue by renatof** [FaaSr/FaaSr-package#85]
Currently, the user is expected to provide a file with credentials to the faasr function, in addition to the JSON workflow configuration. This can lead to the user having multiple files with credentials. 
A better approach would be to allow the user to configure credentials using environment variables instead of files, or to use an existing R package for credential management, if one exists and is sufficiently flexible.

**Comment by spark0510** [comment]
What about `askpass` library? [https://github.com/r-lib/askpass](https://github.com/r-lib/askpass)
We can get user's input and save it in the variable.
